# Generated by Django 4.0.5 on 2022-06-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=65)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('puni', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pkilo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('frutas y Verduras', 'Frutas y Verduras'), ('abarrotes', 'Abarrotes'), ('lacteos', 'Lacteos'), ('carnes', 'Carnes')], max_length=20)),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
