# Generated by Django 4.0.5 on 2022-06-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Frutas y Verduras', 'Frutas y Verduras'), ('Abarrotes', 'Abarrotes'), ('Lacteos', 'Lacteos'), ('Carnes', 'Carnes')], max_length=20),
        ),
    ]
